###
POST http://localhost:4000/user
Content-Type: application/json

{
   
    "Name":"cPaul",
    "Email":"Tal@gmail.com", 
    "Password":"1234qwerQWER"
}


###
POST http://localhost:4000/user/login
Content-Type: application/json

{
   
    "Email":"qeshy@gmail.com", 
    "Password":"qwerQWER1234"
}

###
get http://localhost:4000/user


###
put http://localhost:4000/user
Content-Type: application/json

{
    "userid":8,
    "password":"tbdWyA4787842",
    "name":"PAUL",
    "email":"PAUL2020@gmail.com"
}


###
get http://localhost:4000/user


###
get http://localhost:4000/user/6


###
get http://localhost:4000/user/email/Tali20@gmail.com


###
POST http://localhost:4000/jobs
Content-Type: application/json


{
  "CompanyID": 4,
  "CategoryID": 1,
  "Title": "NodeJS Developer",
  "Description": "A Frontend Developer is a professional specialized in building the visual and interactive elements of a website or web application that users interact with directly. They focus on the client side of development, ensuring that the design and user experience outlined by web designers are translated effectively into a functional user interface.",
  "Location": "Califonia",
  "SalaryRange": "$90,000",
  "Type": "Part-time",
  "PostedDate": "2024-02-01",
  "ExpiryDate": "2024-05-01"
}


###
POST http://localhost:4000/jobs/add
Content-Type: application/json

{
 
 
  "Name": "Frontend Developer",
  "Description": "A Frontend Developer is a professional specialized in building the visual and interactive elements of a website or web application that users interact with directly. They focus on the client side of development, ensuring that the design and user experience outlined by web designers are translated effectively into a functional user interface."
}



###
POST http://localhost:4000/companies
Content-Type: application/json


{

  "Name": "Tech Innovations Inc.",
  "Description": "A leading company in innovative technology solutions, offering a wide range of services and products to enhance business operations and consumer experiences.",
  "Industry": "Technology",
  "Logo": "https://example.com/logo.png",
  "ContactInfo": "info@techinnovations.com"
}



###
get http://localhost:4000/jobs


###
get http://localhost:4000/jobs/Categories/1



###
get http://localhost:4000/category/Categories/


###
get http://localhost:4000/category/Categories/



###
POST http://localhost:4000/categories
Content-Type: application/json

{

  "Name": "Tech Innovations Inc.",
  "Description": "A leading company in innovative technology solutions, offering a wide range of services and products to enhance business operations and consumer experiences.",

}




###
POST http://localhost:4000/companies
Content-Type: application/json

{

  "Name": "Tech Innovations Inc.",
  "Description": "A leading company in innovative technology solutions, offering a wide range of services and products to enhance business operations and consumer experiences.",
  "Industry": "Technology",
  "Logo": "https://example.com/logo.png",
  "ContactInfo": "01010172721",
  "Email":"qeshy@gmail.com", 
  "Password":"qwerQWER1234"
}




###
POST http://localhost:4000/companies/login
Content-Type: application/json

{
   
    "Email":"qeshy@gmail.com", 
    "Password":"qwerQWER1234"
}

###
get http://localhost:4000/companies

###
get http://localhost:4000/admin



###
get http://localhost:4000/admin/companies

###
get http://localhost:4000/companies/applications

###
DELETE http://localhost:4000/admin/delete/1


###
DELETE http://localhost:4000/admin/1

###
DELETE http://localhost:4000/admin/company/1


###
POST http://localhost:4000/apply/4
Content-Type: application/json


{

  "CoverLetter": "A leading company in innovative technology solutions, offering a wide range of services and products to enhance business operations and consumer experiences."

}



###
get http://localhost:4000/apply


###
DELETE http://localhost:4000/apply/


###
get http://localhost:4000/category/



###
get http://localhost:4000/category/Categories/


###
POST http://localhost:4000/category
Content-Type: application/json

{

  "Name": "FrontEnd",
  "UserID": 2,
  "Description": "A leading company in innovative technology solutions, offering a wide range of services and products to enhance business operations and consumer experiences.",

}

